### ISSUE TITLE
ImportError: libiconv.so.2 when trying to import package

### ISSUE THREAD

**Issue by CurtLH** [conda-forge/python-pptx-feedstock#13]
Issue:

After installing this package into a fresh environment, the following `ImportError` is generated:

```python
>>> import pptx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/curtis/Program_Files/miniconda3/envs/my_env/lib/python3.5/site-packages/pptx/__init__.py", line 13, in <module>
    from pptx.api import Presentation  # noqa
  File "/home/curtis/Program_Files/miniconda3/envs/my_env/lib/python3.5/site-packages/pptx/api.py", line 17, in <module>
    from .package import Package
  File "/home/curtis/Program_Files/miniconda3/envs/my_env/lib/python3.5/site-packages/pptx/package.py", line 13, in <module>
    from .opc.package import OpcPackage
  File "/home/curtis/Program_Files/miniconda3/envs/my_env/lib/python3.5/site-packages/pptx/opc/package.py", line 13, in <module>
    from .oxml import CT_Relationships, serialize_part_xml
  File "/home/curtis/Program_Files/miniconda3/envs/my_env/lib/python3.5/site-packages/pptx/opc/oxml.py", line 12, in <module>
    from lxml import etree
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

However, if I `conda install -c conda-forge libiconv`, and then try to import the package, everything works as expected.  For this reason, I believe `libiconv` should be added as a dependency.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/curtis/Program_Files/miniconda3/envs/my_env:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py35_0    conda-forge
freetype                  2.8.1                         0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3  
libpng                    1.6.34               ha92aebf_1    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libxml2                   2.9.8                h422b904_1    conda-forge
libxslt                   1.1.32               h88dbc4e_1    conda-forge
lxml                      4.2.2            py35hc9114bc_0    conda-forge
ncurses                   5.9                          10    conda-forge
olefile                   0.45.1                   py35_0    conda-forge
openssl                   1.0.2o                        0    conda-forge
pillow                    5.2.0                    py35_0    conda-forge
pip                       9.0.3                    py35_0    conda-forge
python                    3.5.5                         1    conda-forge
python-pptx               0.6.10                     py_0    conda-forge
readline                  7.0                           0    conda-forge
setuptools                39.2.0                   py35_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.0                   py35_0    conda-forge
xlsxwriter                1.0.5                      py_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : my_env
    active env location : /home/curtis/Program_Files/miniconda3/envs/my_env
            shell level : 2
       user config file : /home/curtis/.condarc
 populated config files : /home/curtis/.condarc
          conda version : 4.5.5
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/curtis/Program_Files/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/curtis/Program_Files/miniconda3/pkgs
                          /home/curtis/.conda/pkgs
       envs directories : /home/curtis/Program_Files/miniconda3/envs
                          /home/curtis/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.18.4 CPython/3.6.5 Linux/4.4.0-124-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by synapticarbors** [comment]
@CurtLH - Thanks for reporting this. Would you be able to put in a PR to fix the issue?

**Comment by CurtLH** [comment]
I can submit a PR to fix the issue.  But I'm curious as to how any of the [tests](https://github.com/conda-forge/python-pptx-feedstock/blob/master/recipe/meta.yaml#L34) passed without `libiconv`.  Is `libconv` something that was previously pinned, but no longer?

I see there was recently a [similar issue](https://github.com/conda-forge/python-igraph-feedstock/pull/9) with `python-igraph`.
